### ISSUE TITLE
Document suggests 0.2 is newest version, crates.io knows of 0.3

### ISSUE THREAD

**Issue by larswirzenius** [TeXitoi/structopt#257]
This is a very minor issue.

I was reading this page: <https://docs.rs/structopt/0.3.1/structopt/>

It suggests

```toml
[dependencies]
structopt = { version = "0.2", default-features = false }
```

Crates.io tells me of version 0.3.1.

Now, clearly I am a klutz and should just have used crates.io, but it might be kind to future klutzes to either use a ganeric version ("0.x") or explicitly tell the reader to check crates.io, possibly with a link to <https://crates.io/crates/structopt>.
